# Generated by Django 5.1.15 on 2026-09-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='est_archivee',
            field=models.BooleanField(default=False),
        ),
    ]
