# Generated by Django 5.1.15 on 2026-09-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0001_initial'),
        ('reservations', '0002_reservation_est_archivee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='equipement',
        ),
        migrations.AddField(
            model_name='reservation',
            name='equipements',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='equipements.equipement'),
        ),
    ]
