# Generated by Django 5.1.15 on 2026-09-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_reservation_equipement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rappel_envoye',
            field=models.BooleanField(default=False),
        ),
    ]
