# Generated by Django 5.1.15 on 2026-09-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_rappel_envoye'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='rappel_envoye',
            new_name='rappel_1h_envoye',
        ),
        migrations.AddField(
            model_name='reservation',
            name='rappel_24h_envoye',
            field=models.BooleanField(default=False),
        ),
    ]
