# Generated by Django 5.1.15 on 2026-09-23 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
        ('reservations', '0005_rename_rappel_envoye_reservation_rappel_1h_envoye_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='projets.projet'),
        ),
    ]
