# Generated by Django 5.1.15 on 2026-09-30 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0008_equipement_categorie'),
        ('laboratoires', '0003_laboratoire_organisation'),
        ('reservations', '0006_reservation_projet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='motif_refus',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AlerteCreneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_notification', models.DateTimeField(blank=True, null=True)),
                ('equipements', models.ManyToManyField(blank=True, related_name='alertes_creneau', to='equipements.equipement')),
                ('laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_creneau', to='laboratoires.laboratoire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_creneau', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte de créneau',
                'verbose_name_plural': 'Alertes de créneau',
                'ordering': ['date_creation'],
            },
        ),
    ]
