# Generated by Django 5.1.15 on 2026-09-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenances', '0002_maintenance_signale_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='statut',
            field=models.CharField(choices=[('SIGNALEE', 'Signalée'), ('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20),
        ),
    ]
