# Generated by Django 5.1.15 on 2026-09-22 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratoires', '0002_laboratoire_capacite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consommable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('unite', models.CharField(choices=[('ML', 'mL'), ('L', 'L'), ('G', 'g'), ('KG', 'kg'), ('UNITE', 'unité(s)')], default='UNITE', max_length=10)),
                ('quantite_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=1, help_text='Quantité en dessous de laquelle une alerte de stock faible se déclenche.', max_digits=10)),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommables', to='laboratoires.laboratoire')),
            ],
            options={
                'verbose_name': 'Consommable',
                'verbose_name_plural': 'Consommables',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('UTILISATION', 'Utilisation'), ('REAPPROVISIONNEMENT', 'Réapprovisionnement'), ('AJUSTEMENT', 'Ajustement (correction d’inventaire)')], max_length=25)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('consommable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='consommables.consommable')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
