# Generated by Django 5.1.15 on 2026-09-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='date_acquisition',
            field=models.DateField(blank=True, null=True),
        ),
    ]
