# Generated by Django 5.1.15 on 2026-09-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0002_equipement_date_acquisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='consignes_securite',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='instructions_utilisation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='manuel_pdf',
            field=models.FileField(blank=True, null=True, upload_to='manuels_equipements/'),
        ),
    ]
