# Generated by Django 5.1.15 on 2026-09-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0003_equipement_consignes_securite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='necessite_validation',
            field=models.BooleanField(default=False, help_text='Équipement coûteux ou sensible : toute réservation nécessite une validation, quel que soit le rôle du demandeur.'),
        ),
    ]
