# Generated by Django 5.1.15 on 2026-09-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0004_equipement_necessite_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='seuil_heures_maintenance',
            field=models.PositiveIntegerField(default=200, help_text="Nombre d'heures d'utilisation cumulées avant qu'une alerte de maintenance préventive soit déclenchée."),
        ),
    ]
