# Generated by Django 5.1.15 on 2026-09-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0005_equipement_seuil_heures_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='seuil_heures_maintenance',
            field=models.PositiveIntegerField(default=1, help_text="Nombre d'heures d'utilisation cumulées avant qu'une alerte de maintenance préventive soit déclenchée."),
        ),
    ]
