# Generated by Django 5.1.15 on 2026-09-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0007_alter_equipement_seuil_heures_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='categorie',
            field=models.CharField(blank=True, help_text="Ex. 'Microscope', 'Centrifugeuse' — permet de suggérer un équipement équivalent en cas de conflit.", max_length=100),
        ),
    ]
