# Generated by Django 5.1.15 on 2026-09-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='statut_compte',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=20),
        ),
    ]
