# Generated by Django 5.1.15 on 2026-09-18 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_utilisateur_statut_compte'),
    ]

    operations = [
        migrations.CreateModel(
            name='JetonDefinitionMotDePasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeton', models.CharField(db_index=True, max_length=64, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilise', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jetons_mdp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
