# Generated by Django 5.1.15 on 2026-09-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_jetondefinitionmotdepasse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/'),
        ),
    ]
