# Generated by Django 5.1.15 on 2026-09-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_alter_utilisateur_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='statut_academique',
            field=models.CharField(blank=True, choices=[('DOCTORANT', 'Doctorant'), ('MAITRE_DE_CONFERENCES', 'Maître de conférences'), ('PROFESSEUR', 'Professeur des universités')], help_text='Uniquement pertinent pour un enseignant-chercheur ; laissé vide pour les autres rôles.', max_length=30, null=True),
        ),
    ]
