# Generated by Django 5.1.15 on 2026-09-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_utilisateur_statut_academique'),
    ]

    operations = [
        migrations.AddField(
            model_name='jetondefinitionmotdepasse',
            name='motif',
            field=models.CharField(choices=[('INVITATION', 'Activation du compte'), ('REINITIALISATION', 'Mot de passe oublié')], default='INVITATION', max_length=20),
        ),
    ]
