# Generated by Django 5.1.15 on 2026-09-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_jeton_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jetondefinitionmotdepasse',
            name='motif',
            field=models.CharField(choices=[('INVITATION', 'Activation du compte'), ('REINITIALISATION', 'Mot de passe oublié'), ('VERIFICATION', "Vérification de l'adresse email")], default='INVITATION', max_length=20),
        ),
    ]
