# Generated by Django 5.1.15 on 2026-09-30 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('utilisateurs', '0007_jeton_motif_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='encadrant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CHERCHEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants_encadres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super administrateur'), ('ADMIN', 'Administrateur'), ('TECHNICIEN', 'Technicien'), ('CHERCHEUR', 'Membre du laboratoire'), ('ETUDIANT', 'Étudiant')], max_length=20),
        ),
    ]
