# Generated by Django 5.1.15 on 2026-09-12 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('localisation', models.CharField(max_length=150)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('INDISPONIBLE', 'Indisponible')], default='DISPONIBLE', max_length=20)),
                ('photo', models.URLField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laboratoires_geres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laboratoire',
                'verbose_name_plural': 'Laboratoires',
                'ordering': ['nom'],
            },
        ),
    ]
