# Generated by Django 5.1.15 on 2026-09-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoire',
            name='capacite',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
