# Generated by Django 5.1.15 on 2026-09-30 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoires', '0002_laboratoire_capacite'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoire',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratoires', to='organisations.organisation'),
        ),
    ]
