# Generated by Django 5.1.15 on 2026-10-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoires', '0004_unicite_nom_laboratoire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoire',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_laboratoires/'),
        ),
    ]
