# Generated by Django 5.1.15 on 2026-09-30 10:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='Identifiant court, utilisé dans les URL (ex. ucad-fst).', max_length=60, unique=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_organisations/')),
                ('couleur_primaire', models.CharField(default='#1848D9', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Couleur attendue au format hexadécimal, ex. #1848D9.')])),
                ('couleur_secondaire', models.CharField(default='#0F172A', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Couleur attendue au format hexadécimal, ex. #1848D9.')])),
                ('heure_ouverture', models.TimeField(default=datetime.time(8, 0))),
                ('heure_fermeture', models.TimeField(default=datetime.time(19, 0))),
                ('duree_min_reservation', models.PositiveIntegerField(default=30, help_text="Durée minimale d'une réservation, en minutes.")),
                ('duree_max_reservation', models.PositiveIntegerField(default=480, help_text="Durée maximale d'une réservation, en minutes.")),
                ('delai_max_reservation_jours', models.PositiveIntegerField(default=60, help_text="On ne peut pas réserver plus de N jours à l'avance.")),
                ('est_active', models.BooleanField(default=True, help_text='Une organisation suspendue ne peut plus se connecter.')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['nom'],
            },
        ),
    ]
