# Generated by Django 5.1.15 on 2026-10-08 12:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_renommer_organisation_senlab'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraireJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('ferme', models.BooleanField(default=False)),
                ('heure_ouverture', models.TimeField(default=datetime.time(8, 0))),
                ('heure_fermeture', models.TimeField(default=datetime.time(19, 0))),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='organisations.organisation')),
            ],
            options={
                'verbose_name': "Horaire d'ouverture",
                'verbose_name_plural': "Horaires d'ouverture",
                'ordering': ['organisation', 'jour'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'jour'), name='uniq_horaire_jour_par_organisation')],
            },
        ),
    ]
